apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hive-redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hive-redis
    spec:
      containers:
      - name: 
        image: redis:alpine
        ports:
        - containerPort: 6379
          name: hive-redis
---
apiVersion: v1
kind: Service
metadata:
  name: hive-redis
spec:
  ports:
  - port: 6379
  selector:
    app: hive-redis
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hive-front
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hive-front
    spec:
      containers:
      - name: hive-front
        image: mysterygoat/dev_front:v0
        ports:
        - containerPort: 80
        env:
        - name: REDIS
          value: "hive-redis"
---
apiVersion: v1
kind: Service
metadata:
  name: hive-front
spec:
  type: NodePort
    ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hive-back
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hive-back
    spec:
      containers:
      - name: hive-back
        image: mysterygoat/dev_back:v0
        env:
        - name: REDIS
          value: "hive-redis"
