apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hivefiles
  labels:
    sort: learnfiles
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 128Gi
