apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk
  labels:
    sort: learndisk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 128Gi