apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hive-redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hive
    spec:
      containers:
      - name: redis 
        image: redis:alpine
        ports:
        - containerPort: 6379
          name: hive-redis
