apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: polyphony-tensorboard
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: music-rnn
        sort: tensorboard
    spec:
     affinity:
      podAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: sort
              operator: In
              values:
              - learndisk
              - learner
          topologyKey: "kubernetes.io/hostname"
     volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: hivefiles
     containers:
      - name: tensorboard
        imagePullPolicy: Always
        image: tensorflow/tensorflow
        ports:
        - containerPort: 6006
          name: hive-front
        volumeMounts:
        - mountPath: "/mnt/data"
          name: volume
        command: ["bash"]
        args: ["-c", "tensorboard --logdir=/mnt/data/rundir"]
